---
title: "Boston Bike Sharing System Analysis"
author: "Mengyi Zhang and Piaotian Jin"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Boston Bike Sharing System Analysis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  fig.align = "center",
  comment = "#>"
)
library(knitr)
options(width = 100)
```

## 1 Summary

Bike sharing system has received great attention in recent years. As a green way to get around, bike sharing system can relieve the traffic jam in big cities, reduce the emission of harmful gases from motor vehicles, and improve the first mile and last mile connection to other kinds of transits. In 2004, there are about 13 bike sharing systems around the world. But now, there are over 850 bike sharing systems globally.

Boston’s original bike sharing system, Hubway, was launched in 2011, and has changed the name to Bluebikes in 2018. Now, Bluebikes has more than 1,800 bikes and over 200 stations across Boston, Brookline, Cambridge and Somerville.

This project aims to explore the usage patterns of Boston’s bike sharing system, Bluebikes, thus help decision makers to manage the bike sharing system more properly, and promote the full use of Bluebikes.

The primary objectives includes:

1. Explore the usage of Bluebikes from 2015 to 2018. Find out how the number of use and trip durations change among different months. 

2. Use Linear Regression to figure out if there are any relationships between the number of use and the weather.

3. Use hot spot analysis to find out which stations are most popular, what kind of destinations are most popular, what kind of originals are most popular, and how they changed from 2015 to 2018.

4. Use Poisson mixture model to process stations trip count data, extract station clusters based on EM algorithm, and analyze the clusters with census data to find out latent factors contributing to the use of bike sharing system.

5. Summarize the usage profile of BlueBike system and explore if there are any potential areas to promote new bike stations.


## 2 Approach and Method
### 2.1 Data

BlueBike publishes the trip data in csv format each quarter, providing the following information: trip duration, trip start and stop time and date, the id, name and GPS coordinates of start/end station, bike id, and user profile including id, type, gender and birth year. Analyses will be performed on the data from January 2015 to December 2018 in order to generate a comprehensive understanding of the sharing system. Figures below are histograms of BlueBike trip data from 2015 to 2018.

BlueBike also provides another csv file recording the GPS coordinates and the number of docks for each station. The number of trip for each station will be summarized from the trip dataset and joined to the spatial feature of bike station for hot spot and cluster analyses. The figure below presents BlueBike stations and public transportation in Boston area. 

Census data at block group scale is used to extract the demographic characteristics of neighboring community, thus drawing the profile of station clusters. Topics focused in this project are:
Population race
Median household income
Housing units
Means of transportation to work
Aggregated worker’s travel time to work
The source of census data is the estimates of 2017 from 2013-2017 American Community Survey 5-Year Estimates. The following figures visualized the census data.

Shapefiles of Boston area, public transportation, schools, colleges and universities are downloaded from MassGIS, which may contribute to the analysis on latent factors of bike usage. The figure below shows schools, colleges and universities in Boston area.

### 2.2 Code

1. Bluebikes Trips Exploration

Clean up and summarize Bluebikes dataset for further analyses. Use packages tidyverse, dplyr and tidyr to analysis Bluebikes trips data from 2015 to 2018. Use packages ggplot2 to visualize the data. (Piaotian Jin and Mengyi Zhang)

2. Linear Regression

Use R's lm (linear model) function to fit a regression between the number of use and the weather. Find out is there any relationship between the number of use and the weather. (Piaotian Jin)

3. Hot Spot Analysis

Use package hotspots to perform hot analysis on Bluebikes trip data. Find out which stations are most popular, what kind of destinations are most popular, what kind of originals are most popular, and how they changed from 2015 to 2018. (Piaotian Jin)
   
Analyze the demographic characteristics in areas of hot/cold spot clusters. (Mengyi Zhang)

4. Poisson Clusters Analysis

Use package mixtool to conduct Poisson regressions and get the EM algorithm output. Identify station clusters and summarize their profile based on the feature of neighboring communities and demographics. (Mengyi Zhang)

## 3 Timelines
April 15 - April 21: Bluebikes Trips Exploration (Piaotian Jin)

April 15 - April 21: Explore Poisson Clusters Analysis (Mengyi Zhang)

April 22 - April 25: Linear Regression (Piaotian Jin)

April 22 - April 28: Poisson Clusters Analysis (Mengyi Zhang)

April 26 - April 28: Hot Spot Analysis (Piaotian Jin)

April 26 - April 28: Combine the Hot Spot Analysis results with census data (Mengyi Zhang)

April 29 - May 5: Write Final Paper (Mengyi Zhang and Piaotian Jin)

## 4 Anticipated Outcomes
1. Bluebikes Trips Exploration

Plots show how the number of use changes among different months from 2015 to 2018.

Plots show how the trip durations time changes among different months from 2015 to 2018.

2. Linear Regression

Linear Regression results of the number of use and the weather.

3. Hot Spot Analysis

Hot Spot Maps of stations from 2015 to 2018.

4. Poisson Cluster Analysis

Maps of station clusters and corresponding 
